function getDateOffset(days) {
  const date = new Date()
  date.setHours(12, 0, 0, 0)
  date.setDate(date.getDate() + days)
  return date.toISOString().slice(0, 10)
}

export function createMockRides() {
  const today = getDateOffset(0)
  const tomorrow = getDateOffset(1)
  const dayAfterTomorrow = getDateOffset(2)
  const laterDate = getDateOffset(4)

  return [
    {
      id: 'ride-1',
      driverName: 'Ama Owusu',
      driverInitials: 'AO',
      origin: 'Madina',
      destination: 'AmaliTech Office',
      description: 'Via Lagos Avenue, pickup near the main junction.',
      date: today,
      time: '07:30',
      seatsTotal: 4,
      seatsAvailable: 3,
      status: 'open',
      isOwnRide: false,
      requestStatus: 'none',
    },
    {
      id: 'ride-2',
      driverName: 'Kwame Mensah',
      driverInitials: 'KM',
      origin: 'Kasoa',
      destination: 'AmaliTech Office',
      description: 'Leaving early and taking the coastal road.',
      date: tomorrow,
      time: '06:45',
      seatsTotal: 4,
      seatsAvailable: 1,
      status: 'open',
      isOwnRide: false,
      requestStatus: 'none',
    },
    {
      id: 'ride-3',
      driverName: 'Esi Boateng',
      driverInitials: 'EB',
      origin: 'East Legon',
      destination: 'AmaliTech Office',
      description: 'Can pick up around Boundary Road.',
      date: tomorrow,
      time: '08:00',
      seatsTotal: 3,
      seatsAvailable: 2,
      status: 'open',
      isOwnRide: false,
      requestStatus: 'pending',
    },
    {
      id: 'ride-4',
      driverName: 'Yaw Addo',
      driverInitials: 'YA',
      origin: 'Spintex',
      destination: 'AmaliTech Office',
      description: 'Quiet ride, happy to share the route.',
      date: dayAfterTomorrow,
      time: '07:15',
      seatsTotal: 4,
      seatsAvailable: 2,
      status: 'open',
      isOwnRide: false,
      requestStatus: 'accepted',
    },
    {
      id: 'ride-5',
      driverName: 'You',
      driverInitials: 'YO',
      origin: 'Adenta',
      destination: 'AmaliTech Office',
      description: 'Flexible pickup along the Adenta motorway.',
      date: today,
      time: '07:00',
      seatsTotal: 4,
      seatsAvailable: 3,
      status: 'open',
      isOwnRide: true,
      requestStatus: 'none',
    },
    {
      id: 'ride-6',
      driverName: 'Nana Asare',
      driverInitials: 'NA',
      origin: 'Achimota',
      destination: 'AmaliTech Office',
      description: '',
      date: laterDate,
      time: '08:15',
      seatsTotal: 5,
      seatsAvailable: 4,
      status: 'open',
      isOwnRide: false,
      requestStatus: 'none',
    },
    {
      id: 'ride-7',
      driverName: 'Kojo Asante',
      driverInitials: 'KA',
      origin: 'Dansoman',
      destination: 'AmaliTech Office',
      description: 'Pickup close to the roundabout.',
      date: dayAfterTomorrow,
      time: '07:40',
      seatsTotal: 3,
      seatsAvailable: 2,
      status: 'open',
      isOwnRide: false,
      requestStatus: 'none',
    },
    {
      id: 'ride-8',
      driverName: 'Abena Ofori',
      driverInitials: 'AO',
      origin: 'Teshie',
      destination: 'AmaliTech Office',
      description: 'Direct route through Osu.',
      date: laterDate,
      time: '07:20',
      seatsTotal: 4,
      seatsAvailable: 2,
      status: 'open',
      isOwnRide: false,
      requestStatus: 'none',
    },
  ]
}
